# Site settings
title:          Jaeworld's Blog
description:    "Upgrading myself everyday"
url:            "https://jaeworld.github.io"

# Author
author:
  name:         Hyunjae Suh
  url:          
  email:        suhhj2002@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
